server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      name: ${spring.application.name}
      profile: dev
      label: master
      uri: http://${CONFIG_SERVER_NAME:localhost}:${CONFIG_SERVER_PORT:8888}
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
