FROM openjdk:8-jre-buster

ARG VERSION=1.0.0
ARG SERVER_NAME=gateway
ARG SERVER_PORT=9091

LABEL maintainer "myifeng <myifengs@gmail.com>"
LABEL version $VERSION

COPY swan-${SERVER_NAME}-app-${VERSION}.jar /swan/app.jar

HEALTHCHECK CMD curl --fail http://localhost:$SERVER_PORT/actuator/health || exit 1

WORKDIR /swan

ENTRYPOINT ["java","-jar","/swan/app.jar"]